insert into world_happiness(country, score) values ('Finland'', '7.769');
insert into world_happiness(country, score) values ('Denmark'', '7.6');
insert into world_happiness(country, score) values ('Norway'', '7.553999999999999');
insert into world_happiness(country, score) values ('Iceland'', '7.494');
insert into world_happiness(country, score) values ('Netherlands'', '7.4879999999999995');
insert into world_happiness(country, score) values ('Switzerland'', '7.48');
insert into world_happiness(country, score) values ('Sweden'', '7.343');
insert into world_happiness(country, score) values ('New Zealand'', '7.307');
insert into world_happiness(country, score) values ('Canada'', '7.278');
insert into world_happiness(country, score) values ('Austria'', '7.246');
insert into world_happiness(country, score) values ('Australia'', '7.228');
insert into world_happiness(country, score) values ('Costa Rica'', '7.167000000000001');
insert into world_happiness(country, score) values ('Israel'', '7.138999999999999');
insert into world_happiness(country, score) values ('Luxembourg'', '7.09');
insert into world_happiness(country, score) values ('United Kingdom'', '7.053999999999999');
insert into world_happiness(country, score) values ('Ireland'', '7.021');
insert into world_happiness(country, score) values ('Germany'', '6.985');
insert into world_happiness(country, score) values ('Belgium'', '6.922999999999999');
insert into world_happiness(country, score) values ('United Arab Emirates'', '6.825');
insert into world_happiness(country, score) values ('Malta'', '6.726');
insert into world_happiness(country, score) values ('Mexico'', '6.595');
insert into world_happiness(country, score) values ('France'', '6.5920000000000005');
insert into world_happiness(country, score) values ('Chile'', '6.444');
insert into world_happiness(country, score) values ('Guatemala'', '6.436');
insert into world_happiness(country, score) values ('Saudi Arabia'', '6.375');
insert into world_happiness(country, score) values ('Qatar'', '6.374');
insert into world_happiness(country, score) values ('Spain'', '6.354');
insert into world_happiness(country, score) values ('Panama'', '6.321000000000001');
insert into world_happiness(country, score) values ('Brazil'', '6.3');
insert into world_happiness(country, score) values ('Uruguay'', '6.292999999999999');
insert into world_happiness(country, score) values ('Singapore'', '6.2620000000000005');
insert into world_happiness(country, score) values ('El Salvador'', '6.252999999999999');
insert into world_happiness(country, score) values ('Italy'', '6.223');
insert into world_happiness(country, score) values ('Bahrain'', '6.199');
insert into world_happiness(country, score) values ('Slovakia'', '6.1979999999999995');
insert into world_happiness(country, score) values ('Poland'', '6.182');
insert into world_happiness(country, score) values ('Uzbekistan'', '6.1739999999999995');
insert into world_happiness(country, score) values ('Lithuania'', '6.149');
insert into world_happiness(country, score) values ('Colombia'', '6.125');
insert into world_happiness(country, score) values ('Slovenia'', '6.117999999999999');
insert into world_happiness(country, score) values ('Nicaragua'', '6.105');
insert into world_happiness(country, score) values ('Argentina'', '6.086');
insert into world_happiness(country, score) values ('Romania'', '6.07');
insert into world_happiness(country, score) values ('Cyprus'', '6.046');
insert into world_happiness(country, score) values ('Ecuador'', '6.028');
insert into world_happiness(country, score) values ('Kuwait'', '6.021');
insert into world_happiness(country, score) values ('Thailand'', '6.007999999999999');
insert into world_happiness(country, score) values ('Latvia'', '5.94');
insert into world_happiness(country, score) values ('Estonia'', '5.893');
insert into world_happiness(country, score) values ('Jamaica'', '5.89');
insert into world_happiness(country, score) values ('Mauritius'', '5.888');
insert into world_happiness(country, score) values ('Japan'', '5.886');
insert into world_happiness(country, score) values ('Honduras'', '5.86');
insert into world_happiness(country, score) values ('Kazakhstan'', '5.809');
insert into world_happiness(country, score) values ('Hungary'', '5.757999999999999');
insert into world_happiness(country, score) values ('Paraguay'', '5.742999999999999');
insert into world_happiness(country, score) values ('Peru'', '5.697');
insert into world_happiness(country, score) values ('Portugal'', '5.693');
insert into world_happiness(country, score) values ('Pakistan'', '5.653');
insert into world_happiness(country, score) values ('Philippines'', '5.631');
insert into world_happiness(country, score) values ('Serbia'', '5.603');
insert into world_happiness(country, score) values ('Libya'', '5.525');
insert into world_happiness(country, score) values ('Montenegro'', '5.523');
insert into world_happiness(country, score) values ('Tajikistan'', '5.4670000000000005');
insert into world_happiness(country, score) values ('Croatia'', '5.432');
insert into world_happiness(country, score) values ('Dominican Republic'', '5.425');
insert into world_happiness(country, score) values ('Bosnia and Herzegovina'', '5.386');
insert into world_happiness(country, score) values ('Turkey'', '5.372999999999999');
insert into world_happiness(country, score) values ('Malaysia'', '5.3389999999999995');
insert into world_happiness(country, score) values ('Belarus'', '5.3229999999999995');
insert into world_happiness(country, score) values ('Greece'', '5.287000000000001');
insert into world_happiness(country, score) values ('Mongolia'', '5.285');
insert into world_happiness(country, score) values ('Nigeria'', '5.265');
insert into world_happiness(country, score) values ('Kyrgyzstan'', '5.261');
insert into world_happiness(country, score) values ('Turkmenistan'', '5.247000000000001');
insert into world_happiness(country, score) values ('Algeria'', '5.211');
insert into world_happiness(country, score) values ('Morocco'', '5.207999999999999');
insert into world_happiness(country, score) values ('Azerbaijan'', '5.207999999999999');
insert into world_happiness(country, score) values ('Lebanon'', '5.197');
insert into world_happiness(country, score) values ('Indonesia'', '5.192');
insert into world_happiness(country, score) values ('China'', '5.191');
insert into world_happiness(country, score) values ('Bhutan'', '5.082');
insert into world_happiness(country, score) values ('Cameroon'', '5.044');
insert into world_happiness(country, score) values ('Bulgaria'', '5.011');
insert into world_happiness(country, score) values ('Ghana'', '4.996');
insert into world_happiness(country, score) values ('Nepal'', '4.913');
insert into world_happiness(country, score) values ('Jordan'', '4.906000000000001');
insert into world_happiness(country, score) values ('Benin'', '4.883');
insert into world_happiness(country, score) values ('Gabon'', '4.7989999999999995');
insert into world_happiness(country, score) values ('South Africa'', '4.7219999999999995');
insert into world_happiness(country, score) values ('Albania'', '4.718999999999999');
insert into world_happiness(country, score) values ('Cambodia'', '4.7');
insert into world_happiness(country, score) values ('Senegal'', '4.681');
insert into world_happiness(country, score) values ('Somalia'', '4.668');
insert into world_happiness(country, score) values ('Namibia'', '4.638999999999999');
insert into world_happiness(country, score) values ('Niger'', '4.628');
insert into world_happiness(country, score) values ('Burkina Faso'', '4.587');
insert into world_happiness(country, score) values ('Armenia'', '4.559');
insert into world_happiness(country, score) values ('Guinea'', '4.534');
insert into world_happiness(country, score) values ('Georgia'', '4.519');
insert into world_happiness(country, score) values ('Gambia'', '4.516');
insert into world_happiness(country, score) values ('Kenya'', '4.5089999999999995');
insert into world_happiness(country, score) values ('Mauritania'', '4.49');
insert into world_happiness(country, score) values ('Mozambique'', '4.466');
insert into world_happiness(country, score) values ('Tunisia'', '4.461');
insert into world_happiness(country, score) values ('Bangladesh'', '4.456');
insert into world_happiness(country, score) values ('Iraq'', '4.437');
insert into world_happiness(country, score) values ('Congo'', '4.418');
insert into world_happiness(country, score) values ('Congo'', '4.418');
insert into world_happiness(country, score) values ('Mali'', '4.39');
insert into world_happiness(country, score) values ('Sierra Leone'', '4.374');
insert into world_happiness(country, score) values ('Sri Lanka'', '4.3660000000000005');
insert into world_happiness(country, score) values ('Myanmar'', '4.36');
insert into world_happiness(country, score) values ('Chad'', '4.35');
insert into world_happiness(country, score) values ('Ukraine'', '4.332');
insert into world_happiness(country, score) values ('Ethiopia'', '4.2860000000000005');
insert into world_happiness(country, score) values ('Swaziland'', '4.212');
insert into world_happiness(country, score) values ('Uganda'', '4.189');
insert into world_happiness(country, score) values ('Egypt'', '4.166');
insert into world_happiness(country, score) values ('Zambia'', '4.107');
insert into world_happiness(country, score) values ('Togo'', '4.085');
insert into world_happiness(country, score) values ('India'', '4.015');
insert into world_happiness(country, score) values ('Liberia'', '3.975');
insert into world_happiness(country, score) values ('Comoros'', '3.9730000000000003');
insert into world_happiness(country, score) values ('Madagascar'', '3.9330000000000003');
insert into world_happiness(country, score) values ('Lesotho'', '3.802');
insert into world_happiness(country, score) values ('Burundi'', '3.775');
insert into world_happiness(country, score) values ('Zimbabwe'', '3.6630000000000003');
insert into world_happiness(country, score) values ('Haiti'', '3.597');
insert into world_happiness(country, score) values ('Botswana'', '3.488');
insert into world_happiness(country, score) values ('Malawi'', '3.41');
insert into world_happiness(country, score) values ('Yemen'', '3.38');
insert into world_happiness(country, score) values ('Rwanda'', '3.3339999999999996');
insert into world_happiness(country, score) values ('Afghanistan'', '3.2030000000000003');
insert into world_happiness(country, score) values ('Central African Republic'', '3.083');
insert into world_happiness(country, score) values ('South Sudan'', '2.853');
